name: CI

on:
  push:
    branches:
      - master
      - workflows
    tags:
      - '*'
  pull_request:

jobs:
  skipci:
    runs-on: ubuntu-18.04
    steps:
      - run: echo "[skip ci] ${{ contains(github.event.head_commit.message, 'ci:skip') }}"

  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ubuntu-latest]
        dotnet: [ 6.0.x ]
    runs-on: ${{ matrix.os }}

    if: "!contains(github.event.head_commit.message, 'ci:skip')"

    steps:
    - uses: actions/checkout@v2
    - name: Update Submodules
      run: |
        git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore
      run: |
        dotnet tool restore

    - name: Build
      run: |
        dotnet fake build -t Build
      env:
        CI: true

    # - name: Test
    #   run: dotnet fake build -t Test
